### ISSUE TITLE
Crash when initiating a WebKit context menu

### ISSUE THREAD

**Issue by xelxebar** [atlas-engineer/nyxt#1291]
## Overview

Using Slack, when right clicking anywhere, Nyxt crashes with the following output:

```
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING
                                    {10089B8693}>:
  45 is not defined as a value for enum type #<CFFI::FOREIGN-ENUM CL-WEBKIT2:WEBKIT-CONTEXT-MENU-ACTION>.

Backtrace for: #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {10089B8693}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "~S is not defined as a value for enum type ~S." {1006C0FB33}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "~S is not defined as a value for enum type ~S." {1006C0FB33}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "~S is not defined as a value for enum type ~S." {1006C0FB33}>)
3: (ERROR "~S is not defined as a value for enum type ~S." 45 #<CFFI::FOREIGN-ENUM CL-WEBKIT2:WEBKIT-CONTEXT-MENU-ACTION>)
4: (CFFI::%FOREIGN-ENUM-KEYWORD #<CFFI::FOREIGN-ENUM CL-WEBKIT2:WEBKIT-CONTEXT-MENU-ACTION> 45 :ERRORP T)
5: (CL-WEBKIT2:WEBKIT-CONTEXT-MENU-ITEM-GET-STOCK-ACTION #<CL-WEBKIT2:WEBKIT-CONTEXT-MENU-ITEM {1006C0F8C3}>)
6: ((LAMBDA (NYXT::WEB-VIEW NYXT::CONTEXT-MENU NYXT::EVENT NYXT::HIT-TEST-RESULT) :IN FFI-BUFFER-MAKE) #<unused argument> #<CL-WEBKIT2:WEBKIT-CONTEXT-MENU {1006BBAC73}> #<unused argument> #<unused argument>)
7: (GOBJECT::CALL-WITH-RESTARTS #<FUNCTION (LAMBDA (NYXT::WEB-VIEW NYXT::CONTEXT-MENU NYXT::EVENT NYXT::HIT-TEST-RESULT) :IN FFI-BUFFER-MAKE) {52224DFB}> (#<CL-WEBKIT2:WEBKIT-WEB-VIEW {100F9DB183}> #<CL-WEBKIT2:WEBKIT-CONTEXT-MENU {1006BBAC73}> #S(GDK:GDK-EVENT-BUTTON :TYPE :BUTTON-PRESS :WINDOW #<GDK:GDK-WINDOW {1006A156E3}> :SEND-EVENT NIL :TIME 34844049 :X 429.5721130371094d0 :Y 838.262451171875d0 :AXES #(0.0d0 0.0d0) :STATE NIL :BUTTON 3 :DEVICE #<GDK:GDK-X11-DEVICE-XI2 {1006AEE443}> :X-ROOT 429.5721130371094d0 :Y-ROOT 861.262451171875d0) #<CL-WEBKIT2:WEBKIT-HIT-TEST-RESULT {1006BBF5D3}>))
8: ((LAMBDA (GOBJECT::CLOSURE GOBJECT::RETURN-VALUE GOBJECT::COUNT-OF-ARGS GOBJECT::ARGS GOBJECT::INVOCATION-HINT GOBJECT::MARSHAL-DATA) :IN "/gnu/store/rhp5sghv5pk556ad2ghfhhxcc218hxdb-sbcl-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/sbcl/cl-cffi-gtk/gobject/gobject.signals.lisp") #.(SB-SYS:INT-SAP #X7F0B68328590) #.(SB-SYS:INT-SAP #X7F0B779CD9F0) 4 #.(SB-SYS:INT-SAP #X7F0B779CDAA0) #<unused argument> #<unused argument>)
9: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/gnu/store/rhp5sghv5pk556ad2ghfhhxcc218hxdb-sbcl-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/sbcl/cl-cffi-gtk/gobject/gobject.signals.lisp") #<unavailable argument> #<unavailable argument> #<unavailable argument>)
10: ("foreign function: funcall_alien_callback")
11: ("foreign function: callback_wrapper_trampoline")
12: ("foreign function: #x5010086B")
13: ((LAMBDA NIL :IN GTK:ENSURE-GTK-MAIN))
14: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
15: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
16: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
17: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
18: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
19: (SB-THREAD::RUN)
20: ("foreign function: call_into_lisp")
21: ("foreign function: funcall1")

unhandled condition in --disable-debugger mode, quitting
```

## Version Information

```
$ guix package -I nyxt
nyxt    2-pre-release-6 out     /gnu/store/zk06ngmk9zh32acc59v7y1higbvfv3qb-nyxt-2-pre-release-6

$ guix describe
Generation 43	Apr 06 2021 16:33:30	(current)
  guix ab0ed26
    repository URL: https://git.savannah.gnu.org/git/guix.git
    branch: master
    commit: ab0ed26eb70931e04c921ceef313ca67e3c6d61c
```

**Note:** The crash happens both with and without Guix grafts

**Comment by Ambrevar** [comment]
Can you try installing Nyxt with

guix install --no-grafts nyxt

?

**Comment by jmercouris** [comment]
The user says they already tried with and without grafts.

**Comment by Ambrevar** [comment]
On which page and which element exactly does it happen?

If I right-click on slack.com, without being logged in, it works for me.

**Comment by Ambrevar** [comment]
The error message indicates a mismatch between cl-webkit and webkit.  Maybe the cl-webkit context menu bindings are out of date.

**Comment by xelxebar** [comment]
Oh, right. I should have clarified this this is happening when logged in and inside a workspace.

I don't know what I was thinking when I said "clicking anywhere", though. Right-clicking on the message input field crashes. You should see a Slack-specific, custom context menu. Clicking on other places works, variously producing the default context menu or Slack-specific custom ones, depending on click location.

FWIW, I did encounter this issue in the past, but it went away before I got around to submitting a report. Forgive the very rough and ready bug report this time, though. If there is better debug output or sleuthing I can do, please let me know!

**Comment by xelxebar** [comment]
Not sure if it's related, but just *opening* the following URL crashes my nyxt: https://bug-guix.gnu.narkive.com/FagD2Izf/bug-33455-zathura-can-t-display-pdf-or-epub

It happens in both the guix package reported above and in the following one upgraded today:
```
$ nyxt	2-pre-release-6	out	/gnu/store/ad5zfsnx0sx532jlkz778hyaw08zryrp-nyxt-2-pre-release-6
$ guix describe
Generation 44	Apr 10 2021 09:26:15	(current)
  guix f68bcc1
    repository URL: https://git.savannah.gnu.org/git/guix.git
    branch: master
    commit: f68bcc1bc3aa0a8d1829e2eb5d9ef256c817c17c
```

Again, `--no-grafts` makes no difference for me.

**Comment by Ambrevar** [comment]
Can you post the shell output?

I can't reproduce on master.
Could you test against master?
Since you have Guix, it's as easy as cloning this repository and running

  guix package --no-grafts --install-from-file=build-scripts/guix.scm

**Comment by xelxebar** [comment]
Now I'm suspecting my local guix:

```
...
phase `install' succeeded after 4.2 seconds
starting phase `wrap-program'
Backtrace:
           9 (primitive-load "/gnu/store/mh2nypsfdasrr19ybqwswiy14qw…")
In ice-9/eval.scm:
   191:35  8 (_ _)
In guix/build/gnu-build-system.scm:
    838:2  7 (gnu-build #:source _ #:outputs _ #:inputs _ #:phases . #)
In ice-9/boot-9.scm:
  1736:10  6 (with-exception-handler _ _ #:unwind? _ # _)
In srfi/srfi-1.scm:
   857:16  5 (every1 #<procedure 7ffff2b81040 at guix/build/gnu-bui…> …)
In guix/build/gnu-build-system.scm:
   847:30  4 (_ _)
In ice-9/eval.scm:
    619:8  3 (_ #(#(#(#(#(#(#(#(#<directory (g…>) …) …) …) …) …) …) …))
In guix/build/utils.scm:
   1202:8  2 (wrap-program "/gnu/store/siyckv7ik1yzg3c195psh0fhmc55…" …)
In unknown file:
           1 (link "/gnu/store/siyckv7ik1yzg3c195psh0fhmc55bmmw-nyx…" …)
In ice-9/boot-9.scm:
  1669:16  0 (raise-exception _ #:continuable? _)

ice-9/boot-9.scm:1669:16: In procedure raise-exception:
In procedure link: No such file or directory
```

**Comment by xelxebar** [comment]
Okay, I tried to investigate the above error a bit more. For some reason `.../bin/nyxt` isn't getting installed:

```
$ git rev-parse master
ddd5a56213644d6b687407a215a70525777d3513

$ patch -p1 <<'PATCH'
diff --git a/build-scripts/guix.scm b/build-scripts/guix.scm
index 51ae847..bef067d 100644
--- a/build-scripts/guix.scm
+++ b/build-scripts/guix.scm
@@ -134,12 +134,12 @@
                                       (string-append (assoc-ref inputs lib) "/share"))
                                     libs)
                                ":")))
-               (wrap-program bin
-                 `("GIO_EXTRA_MODULES" prefix
-                   (,(string-append glib-networking "/lib/gio/modules")))
-                 `("GI_TYPELIB_PATH" prefix (,gi-path))
-                 `("LD_LIBRARY_PATH" ":" prefix (,path))
-                 `("XDG_DATA_DIRS" ":" prefix (,xdg-path)))
+               ; (wrap-program bin
+               ;   `("GIO_EXTRA_MODULES" prefix
+               ;     (,(string-append glib-networking "/lib/gio/modules")))
+               ;   `("GI_TYPELIB_PATH" prefix (,gi-path))
+               ;   `("LD_LIBRARY_PATH" ":" prefix (,path))
+               ;   `("XDG_DATA_DIRS" ":" prefix (,xdg-path)))
                #t))))))
     ;; We use `cl-*' inputs and not `sbcl-*' ones so that CCL users can also use
     ;; this Guix manifests.
PATCH

$ guix environment --no-grafts --ad-hoc -l build-scripts/guix.scm
$ find $GUIX_ENVIRONMENT
/gnu/store/7lf44kadf7x9ydddki0fq2rv32hqbls5-profile
/gnu/store/7lf44kadf7x9ydddki0fq2rv32hqbls5-profile/lib
/gnu/store/7lf44kadf7x9ydddki0fq2rv32hqbls5-profile/share
/gnu/store/7lf44kadf7x9ydddki0fq2rv32hqbls5-profile/share/info
/gnu/store/7lf44kadf7x9ydddki0fq2rv32hqbls5-profile/share/mime
/gnu/store/7lf44kadf7x9ydddki0fq2rv32hqbls5-profile/share/glib-2.0
/gnu/store/7lf44kadf7x9ydddki0fq2rv32hqbls5-profile/share/applications
/gnu/store/7lf44kadf7x9ydddki0fq2rv32hqbls5-profile/share/icons
/gnu/store/7lf44kadf7x9ydddki0fq2rv32hqbls5-profile/share/doc
/gnu/store/7lf44kadf7x9ydddki0fq2rv32hqbls5-profile/share/man
/gnu/store/7lf44kadf7x9ydddki0fq2rv32hqbls5-profile/manifest
/gnu/store/7lf44kadf7x9ydddki0fq2rv32hqbls5-profile/etc
/gnu/store/7lf44kadf7x9ydddki0fq2rv32hqbls5-profile/etc/profile
```

**Comment by Ambrevar** [comment]
Oops, I recently introduce a regression when I overhauled the
Makefile...

Thanks for reporting, you can try again, it's fixed with 2d28e3094b95a69b96bcb251729ff4133e60a336.

**Comment by Ambrevar** [comment]
Sorry, fixed in 7c4c29e45dccc5abbc4c084164db8e80acc2a50c.

**Comment by iskarian** [comment]
I am running guix as well, and experienced a crash with that same webpage:

```
<INFO> [18:32:07] Loading "https://bug-guix.gnu.narkive.com/FagD2Izf/bug-33455-zathura-can-t-display-pdf-or-epub".
Unhandled SB-INT:SIMPLE-PROGRAM-ERROR in thread #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING
                                                   {100819E653}>:
  invalid number of arguments: 1

Backtrace for: #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {100819E653}>
0: ((LAMBDA (NYXT::WEB-VIEW USER-DATA) :IN FFI-BUFFER-MAKE) #<CL-WEBKIT2:WEBKIT-WEB-VIEW {1007A93A73}>) [external]
1: (GOBJECT::CALL-WITH-RESTARTS #<FUNCTION (LAMBDA (NYXT::WEB-VIEW USER-DATA) :IN FFI-BUFFER-MAKE) {5222505B}> (#<CL-WEBKIT2:WEBKIT-WEB-VIEW {1007A93A73}>))
2: ((LAMBDA (GOBJECT::CLOSURE GOBJECT::RETURN-VALUE GOBJECT::COUNT-OF-ARGS GOBJECT::ARGS GOBJECT::INVOCATION-HINT GOBJECT::MARSHAL-DATA) :IN "/gnu/store/657rp3679fs2z5c2jj9f5288mw505jx8-sbcl-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/sbcl/cl-cffi-gtk/gobject/gobject.signals.lisp") #.(SB-SYS:INT-SAP #X7F82B013EE20) #.(SB-SYS:INT-SAP #X7F82BE8D6200) 1 #.(SB-SYS:INT-SAP #X7F82BE8D62B0) #<unused argument> #<unused argument>)
3: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/gnu/store/657rp3679fs2z5c2jj9f5288mw505jx8-sbcl-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/sbcl/cl-cffi-gtk/gobject/gobject.signals.lisp") #<unavailable argument> #<unavailable argument> #<unavailable argument>)
4: ("foreign function: funcall_alien_callback")
5: ("foreign function: callback_wrapper_trampoline")
6: ("foreign function: #x5010086B")
7: ((LAMBDA NIL :IN GTK:ENSURE-GTK-MAIN))
8: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
9: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
10: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
11: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
13: (SB-THREAD::RUN)
14: ("foreign function: call_into_lisp")
15: ("foreign function: funcall1")
```

After reinstalling from master as suggested above, opening that url no longer crashes *nyxt*. Instead, the page flashes up and seems to do an initial render, then it crashes the buffer:
```
<INFO> [18:40:19] Loading "https://bug-guix.gnu.narkive.com/FagD2Izf/bug-33455-zathura-can-t-display-pdf-or-epub".
<WARN> [18:40:20] Warning: Web process crashed for buffer 5
```

**Comment by Ambrevar** [comment]
I think it's because of the video on the page.
I can reproduce from a container with any page that has videos,
e.g. https://guix.gnu.org.

I can't reproduce outside of a container though.
Either it's a Guix bug or Nyxt is missing some run-time dependency.

**Comment by iskarian** [comment]
I will see if I can test again after Guix 1.2.1 ships with the fixed reference scanning for SBCL.

Otherwise, is there any way to get at the web process's (probably webkit?) logs, stacktrace, etc. to troubleshoot?

**Comment by iskarian** [comment]
Still getting the web process crash on Guix `1eb26d0` and Nyxt `aaa23a5`

**Comment by Ambrevar** [comment]
How do you start Nyxt?

**Comment by xelxebar** [comment]
Tried myself and can reproduce against 27b535e2. It looks like master puts tabs in separate processes, so in this case just the tab crashes. Running simply with `guix environment --no-grafts --ad-hoc --load=build-scripts/guix.scm -- nyxt`.

**Comment by iskarian** [comment]
> 
> How do you start Nyxt?

Simply starting with `nyxt` from the command line, after installing with `guix package --install-from-file=build-scripts/guix.scm` (`--no-grafts` is no longer necessary since the SBCL reference scanning fix shipped)

**Comment by iskarian** [comment]
I am not sure how helpful it is, but I generated two backtraces using 
`gdb --batch --ex "thread apply all bt full" /path/to/WebKitWebProcess core`
from the core dump:

[backtrace.txt](https://github.com/atlas-engineer/nyxt/files/6353901/backtrace.txt)
[backtrace2.txt](https://github.com/atlas-engineer/nyxt/files/6353902/backtrace2.txt)

**Comment by Ambrevar** [comment]
Thanks for investigating.
Sadly I don't know the internals for WebKitGTK enough to understand this
with confidence.

Can you reproduce this issue on every URL?
Can you share URLs where this happens?

**Comment by iskarian** [comment]
> Can you reproduce this issue on every URL? Can you share URLs where this happens?

I've been having trouble narrowing it down but it might occur with video tags when the source is a redirect or a blob... The only other example URL I've found is https://www.taprootvideo.com/test.jsf

Regular embedded webm, ogg, mp4, mp3 do NOT crash.

**Comment by jmercouris** [comment]
Interesting, perhaps we need to be doing some special handling in our context menu. I have a feeling there is a javascript API that handles modification of this menu, and we are misbehaving to it.

@iskarian what happens if you comment out the g-signal connection in `renderer-gtk.lisp` that modifies the context menu?

**Comment by iskarian** [comment]
To be clear, the crash I am talking about occurs just by loading the page -- it loads very briefly then crashes. Xelxebar [mentioned it above](https://github.com/atlas-engineer/nyxt/issues/1291#issuecomment-817092278) and I was corroborating it. Perhaps we need to rename or break out this bug into a separate thread?

**Comment by Ambrevar** [comment]
@iskarian The backtrace you reported https://github.com/atlas-engineer/nyxt/issues/1291#issuecomment-819977089 has been fixed in 04c1e10d67304e2d2dd5af5832485cdcae625a04 3 weeks ago.  You can try master again.

As for the original issue, I guess we would need to leverage WebKitGTK logging to know more about process crashes.

@aartaka Any idea if WebKitGTK has a way to log processes?

**Comment by aartaka** [comment]
[This WebKit debugging article](https://webkit.org/debugging-webkit/) is the only things that I can remember, but it seems to be OSX-specific :(

On a seeming related note: I've recently noticed that we don't respond to some crashing events ([`web-process-terminated`](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html#WebKitWebView-web-process-terminated) specifically). This is the signal increasingly replacing `web-process-crashed`, so we need to bind it. Maybe there are some other signals that we don't handle.

**Comment by jmercouris** [comment]
The video appears/works correctly: 
![Screenshot_20210512_173342](https://user-images.githubusercontent.com/1691662/118002766-3d284a80-b348-11eb-9e10-3500fe0dd05f.png)

**Comment by jmercouris** [comment]
This page also does not crash Nyxt:

![Screenshot_20210512_173518](https://user-images.githubusercontent.com/1691662/118002981-72349d00-b348-11eb-95dc-0a5fbda464db.png)

**Comment by jmercouris** [comment]
As an aside, what is this advertisement on the Guix bug reporters???

**Comment by jmercouris** [comment]
It does not crash on Slack:


https://user-images.githubusercontent.com/1691662/118004302-9fce1600-b349-11eb-926b-798184a9d8bd.mp4

**Comment by jmercouris** [comment]
I believe the renderer is to thank for fixing all of these bugs. In any case, they no longer appear on master. Thank you for your patience and please feel free to reopen if you reencounter these issues!

**Comment by Ambrevar** [comment]
> **Once this is done, the context-menu shouldn't crash Nyxt anymore, even on error.**

It's done on master, sadly this does not work when errors occur during signal handling.  I'm not sure why and I don't if it can be avoided or if it's a limitation of WebKitGTK.

**Comment by Ambrevar** [comment]
> As an aside, what is this advertisement on the Guix bug reporters???

What you are looking at is a mailing list service unrelated to Guix.

For the official Guix issue tracker, see https://issues.guix.gnu.org/.

**Comment by Ambrevar** [comment]
Thank you very much for testing, John!

**Comment by jmercouris** [comment]
No problem!
