### ISSUE TITLE
SBCL/CCL could not find "class*" package

### ISSUE THREAD

**Issue by guojing0** [atlas-engineer/nyxt#1904]
**Describe the bug**

SBCL/CCL could not find `class*` package during building from source when compiling `history-tree.lisp`.

**Precise recipe to reproduce the issue**

I was trying to try out some functionality, so I tried to build the latest version from `master` branch. However, on both macOS and Debian, SBCL/CCL both said that they could not find `class*` package. If I build with nyxt-2.2.3 source code, there is no problem.

In `source/package.lisp`, it was defined
`(trivial-package-local-nicknames:add-package-local-nickname :class* :hu.dwim.defclass-star :nyxt)`
So I could not find where the problem is.

Another question I have is that why does this line
`(trivial-package-local-nicknames:add-package-local-nickname :alex :alexandria)`
appear multiple times across different source files, when it's already defined in `source/package.lisp`?

**Information**
- OS name+version: macOS 10.13.6 and latest Debian
- How you installed Nyxt (Guix pack, package manager, build from source): Source
- Lisp implementation/version (if built from source): Latest SBCL and CCL

**Output when started from a shell**

```
There is no package named "CLASS*" .
   [Condition of type CCL::NO-SUCH-PACKAGE]

Restarts:
 0: [CONTINUE] Retry finding package with name "CLASS*".
 1: [USE-VALUE] Find specified package instead of "CLASS*" .
 2: [MAKE-NICKNAME] Make "CLASS*" be a nickname for package "HISTORY-TREE".
 3: [RETRY-COMPILE-FILE] Retry compiling #P"/Users/Latisp/github/nyxt/libraries/history-tree/history-tree.lisp"
 4: [SKIP-COMPILE-FILE] Skip compiling #P"/Users/Latisp/github/nyxt/libraries/history-tree/history-tree.lisp"
 5: [RETRY] Retry compiling #<CL-SOURCE-FILE "nyxt/history-tree" "history-tree">.
 --more--

Backtrace:
 0: (CCL::%COLLECT-XTOKEN #("CLASS*or-name-tr" 0 6 16 NIL) #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/Latisp/github/nyxt/libraries/history-tree/history-tree.lisp"/4 UTF-8) #x3020067FF56D> #\c)
 1: (CCL::%PARSE-TOKEN #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/Latisp/github/nyxt/libraries/history-tree/history-tree.lisp"/4 UTF-8) #x3020067FF56D> #\c (NIL))
 2: (CCL::%PARSE-EXPRESSION #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/Latisp/github/nyxt/libraries/history-tree/history-tree.lisp"/4 UTF-8) #x3020067FF56D> #\c (NIL))
 3: (CCL::%READ-LIST-EXPRESSION #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/Latisp/github/nyxt/libraries/history-tree/history-tree.lisp"/4 UTF-8) #x3020067FF56D> (NIL) #\))
 4: (CCL::READ-LIST #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/Latisp/github/nyxt/libraries/history-tree/history-tree.lisp"/4 UTF-8) #x3020067FF56D> NIL #\))
 5: (CCL::%PARSE-EXPRESSION #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/Latisp/github/nyxt/libraries/history-tree/history-tree.lisp"/4 UTF-8) #x30200651447D> #\( (NIL))
 6: (CCL::%READ-LIST-EXPRESSION #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/Latisp/github/nyxt/libraries/history-tree/history-tree.lisp"/4 UTF-8) #x30200651447D> (NIL) #\))
 7: (CCL::READ-LIST #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/Latisp/github/nyxt/libraries/history-tree/history-tree.lisp"/4 UTF-8) #x30200651447D> NIL #\))
 8: (CCL::%PARSE-EXPRESSION #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/Latisp/github/nyxt/libraries/history-tree/history-tree.lisp"/4 UTF-8) #x30200651447D> #\( (NIL))
 9: (CCL::%READ-LIST-EXPRESSION #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/Latisp/github/nyxt/libraries/history-tree/history-tree.lisp"/4 UTF-8) #x30200651447D> (NIL) #\))
10: (CCL::READ-LIST #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/Latisp/github/nyxt/libraries/history-tree/history-tree.lisp"/4 UTF-8) #x30200651447D> NIL #\))
11: (CCL::%PARSE-EXPRESSION #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/Latisp/github/nyxt/libraries/history-tree/history-tree.lisp"/4 UTF-8) #x30200651447D> #\( NIL)
12: (CCL::%READ-FORM #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/Latisp/github/nyxt/libraries/history-tree/history-tree.lisp"/4 UTF-8) #x30200651447D> NIL (NIL))
13: (CCL::READ-INTERNAL #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/Latisp/github/nyxt/libraries/history-tree/history-tree.lisp"/4 UTF-8) #x30200651447D> NIL (NIL) NIL)
14: (CCL::READ-RECORDING-SOURCE #<BASIC-FILE-CHARACTER-INPUT-STREAM ("/Users/Latisp/github/nyxt/libraries/history-tree/history-tree.lisp"/4 UTF-8) #x30200651447D> :EOFVAL (NIL) :FILE-NAME "home:github;nyx..
15: (CCL::FCOMP-READ-LOOP "/Users/Latisp/github/nyxt/libraries/history-tree/history-tree.lisp" "home:github;nyxt;libraries;history-tree;history-tree.lisp.newest" 0 #<CCL::LEXICAL-ENVIRONMENT #x302006505FC..
16: (CCL::FCOMP-FILE "/Users/Latisp/github/nyxt/libraries/history-tree/history-tree.lisp" "home:github;nyxt;libraries;history-tree;history-tree.lisp.newest" 0 #<CCL::LEXICAL-ENVIRONMENT #x302006505FCD>)
17: (CCL::%COMPILE-FILE "/Users/Latisp/github/nyxt/libraries/history-tree/history-tree.lisp" "/Users/Latisp/.cache/common-lisp/ccl-1.12-f98-macosx-x64/Users/Latisp/github/nyxt/libraries/history-tree/histo..
18: (COMPILE-FILE #P"/Users/Latisp/github/nyxt/libraries/history-tree/history-tree.lisp" :OUTPUT-FILE #P"/Users/Latisp/.cache/common-lisp/ccl-1.12-f98-macosx-x64/Users/Latisp/github/nyxt/libraries/history..
19: (UIOP/UTILITY:CALL-WITH-MUFFLED-CONDITIONS #<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL UIOP/LISP-BUILD:COMPILE-FILE*) #x30200650676F> NIL)
 --more--
```

**Comment by aartaka** [comment]
> In `source/package.lisp`, it was defined `(trivial-package-local-nicknames:add-package-local-nickname :class* :hu.dwim.defclass-star :nyxt)` So I could not find where the problem is.

> Another question I have is that why does this line `(trivial-package-local-nicknames:add-package-local-nickname :alex :alexandria)` appear multiple times across different source files, when it's already defined in `source/package.lisp`?

You actually found the problem :) Every package needs to define package-local-nicknames independently from other packages. So, to use `class*` local nickname, you need to add it to the `package.lisp` of `history-tree`, much like it's done in `source/package.lisp`.

**Comment by guojing0** [comment]
Thank you @aartaka, it works on `history-tree` now. But the CI on GitHub here can build without any problems. It would be quite tedious to add it to each file that uses `class*`. Since it looks like I am the only one with this issue, what do you think might be the cause? Any thing or set-up I should change?

**Comment by aartaka** [comment]
> Thank you @aartaka, it works on `history-tree` now. But the CI on GitHub here can build without any problems. It would be quite tedious to add it to each file that uses `class*`. 

The thing that eases this is that it's not every file. It's every package. And packages can span lots of files with no need to add nickname setting to those.

Adding to that, in Nyxt sources, every new package can simply call `(use-nyxt-package-nicknames)` and the sane defaults of `alex`, `sera` atc will be established package-locally. See `mode/web.lisp` for an example.

> Since it looks like I am the only one with this issue, what do you think might be the cause? Any thing or set-up I should change?

I'm not sure. Both SBCL and CCL should not complain if the system/package definitions are written correctly.

**Comment by guojing0** [comment]
It may not be the only issue, after building with latest version of `master`, it also displayed

```
CL-USER> (ql:quickload :nyxt/gi-gtk)
To load "nyxt/gi-gtk":
  Load 1 ASDF system:
    nyxt/gi-gtk
; Loading "nyxt/gi-gtk"
Read error between positions 114 and 480 in /Users/Latisp/github/nyxt/libraries/password-manager/password.lisp.
```

That's why I mentioned that it would be tedious to add that to each `package.lisp`...

**Comment by aartaka** [comment]
> That's why I mentioned that it would be tedious to add that to each `package.lisp`...

Well, no other way around there. Either we use full names of packages that they provide or define out own package-local nicknames to all the packages that need them :)

**Comment by jmercouris** [comment]
Well, we could potentially make a reader macro... let's not get into that :-)

**Comment by Ambrevar** [comment]
There is another way: define a global nickname.

To clarify what's happening here: hu.dwim.defclass-star has reverted its `stable` tag to an older commit, which prompted an update of the Quicklisp package.

Then the tag got moved again, this time to a commit containing the `class*` nickname.

So updating Quicklisp should fix it.
This also explains why only Quicklisp users have the problem.
I recommend Nyxt developers to avoid relying on Quicklisp: it may break + it makes reproducibility harder for everyone.

**Comment by Ambrevar** [comment]
@aartaka You could revert the commit you pushed for history-tree.  But it does not hurt either :p

**Comment by guojing0** [comment]
Would you recommend Ultralisp or any other approach?

I ran `(ql:update-all-dists)` and `(ql:update-client)`, and it's still the same result.

**Comment by jmercouris** [comment]
A local checkout of the repository is best so you can pin it to a specific commit.

**Comment by guojing0** [comment]
@jmercouris This one commit https://github.com/atlas-engineer/nyxt/commit/9f4e26f46a3d6873eca0ab3923063e441e7bd9c3 breaks building.

**Comment by jmercouris** [comment]
Indeed, a local commit of defclass* should help you in the interim though. Basically the people of defclass* library made an error, and then reverted it (also reverting the API in the process). By using an older commit, it will still work until they fix it.

**Comment by guojing0** [comment]
Today I update Quicklisp with all latest dists, the issue is resolved.

**Comment by jmercouris** [comment]
Great! :-)
