### ISSUE TITLE
Nyxt freezes when typing very fast in prompt buffer

### ISSUE THREAD

**Issue by Nselm** [atlas-engineer/nyxt#2134]
**Describe the bug**
Nyxts's GUI freezes after typing fast in any prompt buffer with selection filters.

**Precise recipe to reproduce the issue**
When typing fast in the prompt buffer, nyxt just freezes.
A video I had running in the background continued to play, but 
1. I could not do anything 
2. When I switched first to another window, then back, it did not display nyxt anymore, but the previous window

Possibly relevant:
- I have a history of ~100 tabs
- I have ~2000 bookmarks
- I have greatly increased the key repeat rate and reduced the delay (not sure how much, but its probably around twice as fast a normal)

**Information**
- OS name+version:
Arch linux

- Graphics card and driver:
Stoney [Radeon R2/R3/R4/R5 Graphics], AMD

- Desktop environment / Window manager name+version:
i3-gaps 4.20.1-2
- How you installed Nyxt (Guix pack, package manager, build from source):
Nyxt package in aur

- Information from `nyxt --system-information`:
```
Nyxt version: 2.2.4
Renderer version: GI-GTK
Operating system kernel: Linux 5.16.12-arch1-1
Lisp implementation: SBCL 2.2.1 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT
 :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL :21BIT-CHARS
 :CHUNGA :CLOSER-MOP :CL-PPCRE-UNICODE :FLEXI-STREAMS :CL-UNICODE :CL-PPCRE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON :THREAD-SUPPORT :ASDF3.3
 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P
 :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES
 :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL
 :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/nselm/nyxt/src/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/nselm/nyxt/src/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/nselm/nyxt/src/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)
```

**Comment by aartaka** [comment]
What do you mean by selection filters?

**Comment by Ambrevar** [comment]
@Nselm Can you try reproducding this on master?  It may have been fixed already.

**Comment by jmercouris** [comment]
Indeed it is very possible it has been fixed on master. There was some work done recently for a "headless" implementation which fixes some very fast typing/concurrency issues that we potentially did not catch.

**Comment by Nselm** [comment]
I have tried out master and it seems to work.
However: 
1. When typing very fast (esp. deleting, since in this case I just hold down the key) there are still noticeable lags
2. When holding down any key for a longer time, it still hangs.
When I use nyxt normally, those problems do not occur, since I wont press the same key for longer than a few seconds,
so for any practical purposes the problem seems to be fixed.
For reference, the values xset -q gives me:
auto repeat delay:  240    repeat rate:  50

**Comment by Ambrevar** [comment]
We've got an important bug here: I can indeed reproduce the freeze when I keep a key pressed or if I type very fast.

For future reference, to reproduce @Nselm settings, type

```sh
xset r rate 240 50
```

Then keep a key pressed in the `set-url` prompter.

I could not reproduce in `execute-command` though, so it seems that the race condition occurs on CPU-intensive filters.

**Comment by trev-dev** [comment]
Just my totally unhelpful 2 cents here but I believe this bug happens frequently enough for me that I do not have enough confidence in Nyxt to really use it. I can play with it for a while but the expectation is for it to ultimately crash. I can type slow, I can type fast, I can hold buttons down or I could not and it will still crash at the command prompt. This makes Nyxt an unproductive choice for me. 

If there is a reasonable temporary work-around to be had I would implement it.

**Comment by aartaka** [comment]
So, is it fixed? Right now prompt buffer emits "Calculating..." message on new input. Is that the fix in action?

**Comment by Ambrevar** [comment]
No no no, nothing is fixed yet, it will come with the concurrency overhaul.

**Comment by timthelion** [comment]
I presume this freeze is the same issue? I see an error at the bottom of the screen as well as the obvious total freeze (see the overdraw from my launcher...).

![image](https://github.com/atlas-engineer/nyxt/assets/1391608/8de9386d-76e8-43be-b72d-a8e43e448bab)

**Comment by jmercouris** [comment]
Hello @timthelion you are using a rather old version of Nyxt, can you please try on latest 3.0.0 :-)?

**Comment by Ambrevar** [comment]
Note that the original post issue is not fixed on 3.0.0.

**Comment by odanoburu** [comment]
Can confirm I still get freezes fairly often. My machine is otherwise fast, RAM is far from exhausted, and I have been trying out Nyxt (3rd attempt) for just a day, so not a long history nor long list of bookmarks etc.

**Comment by odanoburu** [comment]
Indeed. My openssl version is 3.1.1, so it should have [this function](https://www.openssl.org/docs/man3.0/man3/SSL_get1_peer_certificate.html). Not sure of the version used in the flatpak though.

**Comment by odanoburu** [comment]
I think the hanging issue is related to garbage collection: increasing the the amount of memory that will be allocated before the next garbage collection is initiated (by setting `sb-ext:bytes-consed-between-gcs`) seems to delay the hanging — although of course when it does come it hangs even longer because there is more garbage to collect. I also tried decreasing this value so that the GC would run more often (but taking less time), but I not could find a value that would stop the hanging. SBCL's GC is not low-latency, after all. Although there are efforts towards a better GC:

https://applied-langua.ge/~hayley/swcl-gc.pdf (parallel GC in SBCL >2.3.8)
https://github.com/sbcl/sbcl/blob/master/doc/internals-notes/arena-allocation.txt (arena allocation reduces the need for garbage collection)
https://groups.google.com/g/sbcl-devel/c/VAA4SkQo3jM (work on low latency GC)

Not sure how much the nyxt team has looked into this, I can open a separate issue or discussion if you prefer. The simplest attempt at a solution (that does not require waiting for SBCL development) would be to trigger the GC manually very frequently, and running a full GC run when the there is no user input.

**Comment by odanoburu** [comment]
> Let's assume that the root cause is related to SBCL's GC. How does that fit into the fact that the issue is observed in the Flatpak but not on Guix?

The only thing I could think of is Guix's SBCL version already having the parallel GC, it being the default, and it solving the problem. That's a bit of a stretch, however.

How much RAM does your machine have?

**Comment by odanoburu** [comment]
I see. The one I used has 16GB. I asked because the default heap size seems to be a fraction of the machine's RAM, and the default GC threshold seems to be a fraction of the heap size.

**Comment by Ambrevar** [comment]
From the error I doubt this has to do with the RAM, rather with the SSL binding: it seems that the SSL lib found at runtime does not exactly match the one used at compile time.  Differences between Flatpak and Guix are to be expected here.

In anycase, this seems to be unrelated to this issue, I propose to open a new issue about  this.

**Comment by odanoburu** [comment]
André and I have been talking about too many things, so it got a bit confusing, @Ambrevar, sorry about that. The RAM part was part of a discussion about Nyxt hanging (this issue). To check whether this problem occurred in the non-Flatpak version of Nyxt, I compiled Nyxt from source, which got me the SSL error I mentioned. This was more of a side comment, and indeed might deserve its own issue.

**Comment by odanoburu** [comment]
Ok, thank you.

By the way, I resolved the OpenSSL problem I mentioned above, and wrote this issue as documentation in case anyone has the same problem: https://github.com/atlas-engineer/nyxt/issues/3286

**Comment by tomterl** [comment]
I had freezes all the time (since I first learned about nyxt a couple of years ago) - when interacting with nyxt-prompts and recently when creating a new window; I therefore never used nyxt over a couple of minutes evaluation time here and then (till a hard freeze occured).

After finding this issue here, I installed sbcl 2.4.0 and used the release-source-tar-ball with submodules to build nyxt from -- I cannot reproduce the freezes and have the browser running almost 24h now.

**Comment by odanoburu** [comment]
I'm sad to report that updating to sbcl 2.4.0 and the current master of Nyxt (commit e7228d23e) does not solve the issue for me. Maybe @tomterl enabled some compilation flag I haven't?

@aadcg if you would be open to that we could schedule a call and try to fix it by pair programming?

**Comment by tomterl** [comment]
For the record: All I did was `export LISP="~/opt/sbcl/bin/sbcl --dynamic-space-size 3072 "` and than `make all`; I did not compile sbcl by myself, I used the binary release `sbcl-2.4.0-x86-64-linux`. 

I tried to attach gdb to the running process after the flatpak version freeze, but apparently one needs a magic incantation to debug a flatpak process, and I didn't have the time to dig into that (still don't, really).

**Comment by tomterl** [comment]
> > are there differences in the build-process between a release-tarball and master?
> 
> No differences, in the sense that `make all` should work in the same way in both settings.
> 
> > one needs a magic incantation to debug a flatpak process
> 
> It's fairly straighforward, see https://docs.flatpak.org/en/latest/debugging.html.
> 
> @tomterl does that mean that you experience freezes in the Flatpak but not when compiling yourself?

Yes, as I wrote in my initial interaction:
> I had freezes all the time (since I first learned about nyxt a couple of years ago) - when interacting with nyxt-prompts and recently when creating a new window; I therefore never used nyxt more than a couple of minutes evaluation time here and then (till a hard freeze occured).

**Comment by odanoburu** [comment]
I have gone back to my default nyxt installation (
```
Nyxt version: 4
Renderer: GI-GTK
Operating system kernel: Linux 6.6.13-200.fc39.x86_64
Lisp implementation: SBCL 2.3.6-2.fc39 (Dynamic space size: 3221225472)
ASDF version: 3.3.1
```
), connected to it via SLY, and profiled (using SBCL's sprof) Nyxt while reproducing the bug twice. See the attached logs, each one in one of sprof's modes (:cpu, :clock, :alloc).
[time.log](https://github.com/atlas-engineer/nyxt/files/14098079/time.log)
[cpu.log](https://github.com/atlas-engineer/nyxt/files/14098080/cpu.log)
[alloc.log](https://github.com/atlas-engineer/nyxt/files/14098081/alloc.log)

I hope this helps; it would be nice if we could know what the syscall taking up most of the time in time.log was (is there any way to find out?) I welcome any improvements to the profiling code, which currently is simply
```lisp
(sb-sprof:start-profiling :max-samples 10000 :mode :cpu)
;; reproduce the bug in Nyxt twice: call set-url, press the 'k' key in 
;; the keyboard and hold it until Nyxt freezes, press 'k' repeatedly 
;; until Nyxt finally comes back, press 'k' repeatedly until Nyxt 
;; freezes again, press 'k' until Nyxt unfreezes, then go back to 
;; SLY and run
(sb-sprof:stop-profiling)
(sb-sprof:report :type :flat)
```

I'd prefer to use the `with-profiling` macro, but I don't know how to call a command from the SLY repl (does Nyxt have anything akin to Emacs' `call-interactively`?

It would also be nice to know if there is a way to profile by thread — does anyone have any pointers on how to do that?

**Comment by tomterl** [comment]
I am sorry to say, that I encounter freezes again, with my own build.  I attached gdb, but there are too many threads to make sense of at a glance, and I'm at work.  FWIW I (also) think that key-input-rate is a red herring, or the freezes I encounter are unrelated - I don't type that fast :).

**Comment by tomterl** [comment]
> @tomterl are the freezes related to the prompt buffer?

It would appear so, but it is hard to tell, as almost any interaction with Nyxt, other than scrolling, involves the prompt buffer - or am I understanding the term wrong? One freeze occured after executing `make-window` from the comand prompt (`:`), a couple more after editing the url both `o` and `O` and pressing the final `return`.

**Comment by odanoburu** [comment]
@aadcg This will come as no surprise to you, but I tested Nyxt on my old machine and indeed I cannot reproduce the freezing there. Nyxt is the only application that freezes so on my current machine though, so even if it's not related to Nyxt I still can't make it my daily driver, despite how much I'd like to do so. I tried increasing the delay between key repeats and decreasing their speed (I'm on Wayland so I couldn't run your command directly), but Nyxt still freezes. As I said before, holding the key down is just the easiest way of reproducing the issue, but if I just type at regular speed — and I don't don't type super fast — Nyxt will hang.

**Comment by tomterl** [comment]
Despite setting `DEBUGINFOD_URLS="https://debuginfod.archlinux.org/"` and waiting for my slow connection to fetch a metric ton of debug information, the traces I got from gdb are lacking a lot of details.

Nevertheless: https://paste.sr.ht/~tomterl/1d6be5cc3b86e6e67e9b890f11a5333ea9b100ab

Maybe something catches your eye - I'll try to get the correct symbols somehow, to make more details visible.

**Comment by tomterl** [comment]
> @tomterl thanks for the investigation! Nothing catches my eye. What executable did you use in the debugger - a local build or via Flatpak? 

A local build

**Comment by odanoburu** [comment]
> Occasional crashes may happen due to WebKitGTK, but it is not acceptable if Nyxt crashes often when using the prompt buffer.

Yeah, unfortunately it freezes even when I'm trying to set-url for the first time,  with no pages open and without loading any configuration.

> I'd love to understand why, i.e. why you can't reproduce in your old machine.

It's pretty weird, isn't it? I'm running Wayland on both machines, yes. I installed Nyxt from the flatpak in the old machine, in the new one I tried both flatpak and source-built versions.

I guess my next step would be running Debian on my new machine — it currently runs Fedora. If that works, it's either Fedora-related or some customization I made (could it be using IBus as my IME?). I have recently installed Debian on the old machine and I haven't configured everything yet, so it's pretty close to out-of-the-box Debian.

**Comment by odanoburu** [comment]
Both have integrated Intel GPUs. The new machine sometimes has driver issues because the hardware is a bit too new (the camera still doesn't work reliably or fully under Linux), so it might be something like this, although I have never experienced any freezes with any other app.

**Comment by tomterl** [comment]
The only thing every platform/release-format I tried had in common is a tiling WM - Distros: Ubuntu 18.04 up to 22.04 (same machine, occasional LTS Updates), manjaro (arch based) - nvidia GPU card, internal intel GPU.

**Comment by odanoburu** [comment]
@aadcg I can't freeze it by simply pressing a key like I can on `set-url`, no. Which is interesting…

**Comment by odanoburu** [comment]
That solved the freezing, but it is strange that it didn't happen on my old machine (using the same network). I used to get freezes all the time, not just when the network is acting up, although I guess what matters here is latency, not so much speed (maybe the servers being contacted are far from me). Or maybe the network driver of the new machine is bad.

Anyway, as you said on that issue, there should be a timeout for fetching the requests. And even if there isn't, the input shouldn't block because the requests should be asynchronous.

Thank you for the help and patience @aadcg, I can use Nyxt more extensively now!

**Comment by odanoburu** [comment]
Maybe one can reproduce the problem throttling one's network, using [netem](https://man7.org/linux/man-pages/man8/tc-netem.8.html) on Linux, there are some examples of how to use it on the man page. Out of curiosity, I'll try Nyxt without this patch whenever I'm on another network, and will also try to make more tests on my old machine to see if it ever reproduces this bug.

**Comment by odanoburu** [comment]
Simply doing

```diff
     (lambda (suggestions source input)
       (declare (ignore suggestions source))
       (input->queries input
-                      :check-dns-p t
+                      :check-dns-p nil
                       :engine-completion-p t)))
    (prompter:actions-on-return #'buffer-load*))
   (:export-class-name-p t)
```

seems to be enough to not freeze Nyxt on my machine.

**Comment by tomterl** [comment]
Setting `:check-dns-p nil` seems to be enough to prevent freezes on my end, too.
