### ISSUE TITLE
Buffer crashes on zsa.io and Gmail

### ISSUE THREAD

**Issue by shonfeder** [atlas-engineer/nyxt#2136]
**Describe the bug**

Buffer is crashing when visiting https://www.zsa.io/moonlander with message:

```
WARN - Warning: Web process terminated for buffer 20 (opening https://www.zsa.io/moonlander/) because it crashed
WARN - Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: 
```

**Precise recipe to reproduce the issue**

I can currently reproduce this everytime time I navigate to https://www.zsa.io/moonlander. I have hit buffer crashes with the same message while trying to load Gmail (perhaps a good sign to get off google!). In case it is relevant, I first hit the problem when trying to login to a secondary account on GMail.

For website-specific issues:
Can you reproduce this issue with Epiphany / GNOME Web (https://wiki.gnome.org/Apps/Web)?

I cannot reproduce this on either GMail or zsa.io on Epiphany. I tried loading zsa.io both before and after logging in to GMail: it works fine. 

**Information**
- OS name+version: `Ubuntu 21.04`
- Graphics card and driver: `00:02.0 VGA compatible controller: Intel Corporation CometLake-U GT2 [UHD Graphics] (rev 02)` (Mesa INtel UHD Graphics)
- Desktop environment / Window manager name+version: `GNOME, 3.38.5
- How you installed Nyxt (Guix pack, package manager, build from source): `.deb package from from site`
- Information from `show-system-information`:

```
System information

Nyxt version: 2.2.4
Renderer version: GI-GTK
Operating system kernel: Linux 5.15.15-76051515-generic
Lisp implementation: SBCL 2.1.0.0.HEAD.1-46cb065 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42
 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56
 :GLIB-2-58 :GLIB :NYXT-2 :FSET-EXT-STRINGS :CUSTOM-HASH-TABLE-NATIVE :SWANK
 :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES :PARENSCRIPT :NAMED-READTABLES
 :LPARALLEL :21BIT-CHARS :CHUNGA :FLEXI-STREAMS :CLOSER-MOP :CL-PPCRE-UNICODE
 :CL-UNICODE :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CHIPZ-SYSTEM:GRAY-STREAMS
 :FAST-IO-SV :FAST-IO :SBCL-USES-SB-ROTATE-BYTE :CL-JSON-CLOS :CL-JSON
 :THREAD-SUPPORT :CL-PPCRE CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64
 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP
 :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.4
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/home/runner/work/nyxt/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/runner/work/nyxt/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /home/runner/work/nyxt/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)

Guix version: 
```

**Comment by shonfeder** [comment]
This is just my first half-day trying nyxt, and I'm loving it so far :heart_eyes_cat: . Really wonderful work!

**Comment by aartaka** [comment]
Hmmmmm. I cannot reproduce, both Gmail and Moonlander page work fine on my Nyxt (built from master). Several things to try there:
- Ensure you're using the most recent release of WebKitGTK. We depend on lots of its features and the experience is best with fresh WebKitGTK.
- Try building from source, if you can, or wait for the upcoming 3.0 release. It may well be the case that we have already fixed this problem.

**Comment by shonfeder** [comment]
Thanks for the tips! I'll try both of these when I get a chance.

**Comment by shonfeder** [comment]
As an update: 

- I've built nyxt from source on `master` (which has actually resulted in an older version `2.1.1-1812-gb040ee43`, but presumably that is a specious artifact of the version-reporting system rather than anything of concern?) and the crash still occurs.
- I've not yet updated WebKitGTC, which looks like it will also require building from source, as I am already using the latest available version on apt.

**Comment by aartaka** [comment]
Hmmmm, the version seems recent enough. I'm not sure what's there that may differ so that I cannot reproduce. 

Anyone else with these particular websites crashing?

**Comment by jmercouris** [comment]
You may also try using the Guix pack which may use a new version of WebKitGTK+ than what is available via apt-get.

**Comment by aartaka** [comment]
@Nazar65 

> Hello here, i have same problem with github, on 2 and 3-pre-release version, like when i try to submit a review or use the filter the buffer crashes with the : `WARN - Warning: Web process terminated for buffer 117336 (opening https://github.com/atlas-engineer/nyxt/issues/2374) because it crashed WARN - Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: `

This I can reproduce and it's annoying as hell. Seems to be WebKit-side problem, though.

**Comment by Ambrevar** [comment]
Which filter?  If you mean the file filters in GitHub PR reviews, it works fine for me.

**Comment by Nazar65** [comment]
@Ambrevar the reason is that is not stable issue, it can work on some issues, and on some i even not able to open issue via link, it is just crashing with the above message. And it's really annoying since  i need to switch to ther browser to be able to finish review, or open the issue.

**Comment by Nazar65** [comment]
@Ambrevar  for example i;m able to open this issue via link in notification, but from issues pages, it is crashing as well

**Comment by Nazar65** [comment]
Hello there, just and update, looks like it is related to the history file in my case default.lisp, i got some segmentation fault, and to resolve this i removed the history file, and  now all working as well, no random buffer crashes so far.

**Comment by Ambrevar** [comment]
This is very odd.  Please if you hit this issue again, could you share your history file?  You can censor it if you like.  Otherwise a recipe maybe?

**Comment by aadcg** [comment]
Both URLs render without issues  as of commit 28c6ad3 and WebKitGTK version 2.40.1.
