### ISSUE TITLE
Re-opening "FreeBSD build failure: lfp.h not found even with libfixposix installed #1820"

### ISSUE THREAD

**Issue by ko56** [atlas-engineer/nyxt#2138]
I am having the same problem with lfp.h not found on FreeBSD 13.0, using cc (i.e. clang) and SBCL 2.2.0.
To build nyxt I did as suggested in the README

```
mkdir -p ~/common-lisp
git clone https://github.com/atlas-engineer/nyxt ~/common-lisp/nyxt
```
and then

`gmake all`

I read the last comment in #1820, i.e. 
Edit.: [fixed upstream.](https://github.com/sionescu/iolib/commit/548537ed0c764ed00f7dfa703e5e51506c19460f)

but, curiously, when I look at my 

`common-lisp/nyxt/_build/iolib/src/os/ffi-types-unix.lisp`

I see a version that does not include the fix.  
Help would be appreciated.

**Comment by Ambrevar** [comment]
Thanks for reporting, I've updated the iolib submodule to the latest commit, it should now be working.

**Comment by ko56** [comment]
Thank you. I am not very familiar with git, how do I proceed now?  
Do I have to delete everything and re-clone the whole repository?

**Comment by Ambrevar** [comment]
That would work but you can also simply run this from the Nyxt checkout:

    git submodule  update --init --remote _build/iolib

**Comment by ko56** [comment]
Sorry, I just realized the `cc` line is still wrong.  It should have -I/usr/local/include.  And the flags look like they are for gcc.  Maybe there's something more I have to do?

**Comment by Ambrevar** [comment]
Do you have `pkg-config` installed?

**Comment by ko56** [comment]
Yes.
```
ko@wiley ~]$ pkg-config -cflags libfixposix
-I/usr/local/include -D_XOPEN_SOURCE=600 -D__BSD_VISIBLE -D_THREAD_SAFE -pthread 
[ko@wiley ~]$ 
```

**Comment by ko56** [comment]
I see the problem.  For some reason the file `_build/iolib/src/os/ffi-types-unix.lisp` is still the old version, even though its date is 9 March:

```
;;;; -*- Mode: Lisp; indent-tabs-mode: nil -*-
;;;
;;; --- Foreign types related to lfp_spawn(3)
;;;

(in-package :iolib/os)

(include "lfp.h")

(constant (+stdin+  "STDIN_FILENO"))
(constant (+stdout+ "STDOUT_FILENO"))
(constant (+stderr+ "STDERR_FILENO"))

(cstruct lfp-spawnattr-t "lfp_spawnattr_t")

(cstruct lfp-spawn-file-actions-t "lfp_spawn_file_actions_t")

(constant (lfp-spawn-setsigmask    "LFP_SPAWN_SETSIGMASK"))
(constant (lfp-spawn-setsigdefault "LFP_SPAWN_SETSIGDEFAULT"))
(constant (lfp-spawn-setpgroup     "LFP_SPAWN_SETPGROUP"))
(constant (lfp-spawn-resetids      "LFP_SPAWN_RESETIDS"))
(constant (lfp-spawn-setuid        "LFP_SPAWN_SETUID"))
(constant (lfp-spawn-setgid        "LFP_SPAWN_SETGID"))
(constant (lfp-spawn-usevfork      "LFP_SPAWN_USEVFORK"))
;; (constant (lfp-spawn-setschedparam "LFP_SPAWN_SETSCHEDPARAM"))
;; (constant (lfp-spawn-setscheduler  "LFP_SPAWN_SETSCHEDULER"))

```

**Comment by Ambrevar** [comment]
To be sure, delete the Nyxt repo and try again :)

**Comment by ko56** [comment]
OK, the build works with no problems now.

**Comment by graeme3317** [comment]
I decided to clone and build on FreeBSD 13.2 and have hit the same problem as above. 

I did a build a while back (6 months ?) which was successful and  where ffi-types-unix.lisp has the line:

`(pkg-config-cflags "libfixposix")`

That line is missing from the current version but it is present in the version of the file in the build/nfiles subdirectory:

`:~/common-lisp/nyxt$ find . -iname "ffi*.lisp" -exec grep -Hi 'pkg-config' {} \;

./_build/nfiles/_build/iolib/src/syscalls/ffi-types-unix.lisp:(pkg-config-cflags "libfixposix")
./_build/nfiles/_build/iolib/src/os/ffi-types-unix.lisp:(pkg-config-cflags "libfixposix")
./_build/iolib/src/syscalls/ffi-types-unix.lisp:;;; FIXME: Find a way to use pkg-config to get these flags
`
I don't know enough about the build process to work out what is going on, but any pointers would be appreciated
