### ISSUE TITLE
Input methods don't work in the minibuffer

### ISSUE THREAD

**Issue by acidtoyman** [atlas-engineer/nyxt#324]
I'm on Debian, and on Next 1.3, non-Latin characters don't display.  This is a big deal for me, as I live in Japan.

**Comment by Ambrevar** [comment]
How did you install Next?

Where doesn't it display?  In the web views or in the minibuffer?

**Comment by acidtoyman** [comment]
I'm running the complete bundle of 1.3.0 from the download page.  The characters don't display in either the web views or minibuffer—no boxes or anything, just blank spaces wherever there's a non-Latin character.

**Comment by Ambrevar** [comment]
Do non-Latin characters display in a browser like Epiphany (GNOME web)?

If not, then there is an issue with your system configuration (you might
need some extra packages).

If yes, then the issue is probably due to the Guix pack.

You can either:

- Install Guix, the Next Guix channel and then run `guix install next`
as per the readme.

- Install from souce (`make next`: see the developer's documentation).

Let me know if you need more help.

Ideally, we would need someone to provide a .deb, that would help Debian users.

**Comment by acidtoyman** [comment]
Non-Latin characters display for me properly in epiphany-browser, conkeror, Chrome, Firefox, and Waterfox.  I'll try to find the time to try out your other suggestions.

**Comment by vindarel** [comment]
Related: I cannot type non-latin characters in the minibuffer (for example, tilde-letter such as `ñ`). Typing the tilde prints "dead_perispomeni".

**Comment by Ambrevar** [comment]
More specifically: I cannot type dead keys.
I can insert "ñ" directly however.

So yeah, we need to enable dead-key support.

**Comment by acidtoyman** [comment]
Minor update: the issue persists in 1.3.1.

**Comment by Ambrevar** [comment]
Indeed, 1.3.1 was a minor update, we've still got a bunch of important
issues to address.  Hopefully soon, stay tuned!

**Comment by Ambrevar** [comment]
I've just pushed a fix for dead keys in aebc9110723dddeb3f83f167b92e964e0a60d310.
Does that work for you, @acidtoyman ?

How do you input non-latin characters?

By the way, while working on the issue I realized that web view input should be unaffected.  You mentioned that you could not input non-latin characters in web views above, so this might be a different issue.

Also now that we have a .deb, you should be able to install easily install Next in a more Debian-integrated way:
https://github.com/atlas-engineer/next/issues/76#issuecomment-535060295

**Comment by acidtoyman** [comment]
That's done the trick!  Thank you so much!

I didn't notice you'd said there was a .deb, so I tested from source.  Glad to know there's a .deb now, but unforrtunately I'm getting a 502 on the download page.  Will there be a repository to make updating easy?

**Comment by acidtoyman** [comment]
Oh, and actually, it was vindarel who mentioned not being able to type non-latin characters.  I notice this is a problem for me, too.  When I hit the "hankaku_zenkaku" key (which switches between English and Japanese input), instead of swtiching inputs it inserts the string "Hankaku_Zenkaku" in the minibuffer (is this what you mean by "web views"?).  This happens only in the minibuffer—if I open, say, google.com and input in Google's search box, I don't have this problem.

**Comment by Ambrevar** [comment]
.deb: The website was down, it's up again.

I'll work on the "Hankaku_Zenkaku" issue, I think I've got an idea how to fix this once and for all! :)

**Comment by Ambrevar** [comment]
Should be fixed with 533e0b5be0da53d85ef997f0b7834810889b07de: now all GTK-supported keys should be supported in the minibuffer.

Also unicode input works, even though the underlined "u" is not displayed:
`C-S-u 123 SPACE` outputs `ģ`.

**Comment by Ambrevar** [comment]
Sorry, `C-s-u 123 SPACE`
(Control Shift u).

**Comment by acidtoyman** [comment]
Thanks.  The solution partially worked.  I can now input using the "compose" key* (so things like "ü" or "→"), but when I press "hankaku_zenkaku", nothing happens.  It no longer inserts the string "hankaku_zenkaku", but it also doesn't switch to Japanese input (but I still get Japanese input outside of the minibuffer, for example in the Google search bar).

* (I have "insert" remapped to "compose" on my system—Japanese keyboards don't have a "compose" key)

**Comment by Ambrevar** [comment]
Well, we are making progress! :)

Sorry I'm a bit ignorant about the hankaku_zenkaku key, so I have few
questions:

- Is it a "switch" key, i.e. you press and release it, or is it a
modifier, i.e. you need to keep it pressed?

- When the minibuffer is down and you switch to Japanese input, then
bring the minibuffer up, can you get Japanese input in the minibuffer?

**Comment by jmercouris** [comment]
How could you bring up the minibuffer when japanese input mode is selected?

**Comment by Ambrevar** [comment]
Any binding would do.

**Comment by jmercouris** [comment]
Right, but how would you use any binding when a Japanese input mode is selected? None of them are bound to any Japanese characters.

**Comment by Ambrevar** [comment]
They can be in init.lisp.

Besides, I assume some of Latin / punctuation / numeral keys remain, like the numeric keypad.

**Comment by jmercouris** [comment]
I didn't know we could bind non-latin characters! Very cool!

**Comment by acidtoyman** [comment]
It's a "switch" to allow using Roman input to input Japanese, so that by pressing the keys D-E-R-U, it gives you a list of potential Japanese words to choose from that have that pronunciation.  This type of input is common for Japanese, Chinese, and Korean.  On Windows, the software's called Microsoft IME; there are quite a few different input methods for Linux.  I use [fcitx](https://fcitx-im.org/wiki/Fcitx), and have used IBus and [SCIM](https://github.com/scim-im/scim) in the past.

**Comment by Ambrevar** [comment]
Understood.  So what happens if you switch to japanese input outside the minibuffer, then bring up the minibuffer?  Can you type anything then?

Can you provide precise recipe of what works and what doesn't?

**Comment by acidtoyman** [comment]
Hmm ... doesn't work.  I typed some Japanese text into the Google search bar, pressed C-l, and got only Latin text in the minibuffer.  When I tried it with C-l, it didn't even allow me to type into the minibuffer—the text (which was Japanese) appeared in the Google search bar, even though the minibuffer was open.  I could input in the minibuffer only after clicking somewhere out of the Google search bar before doing C-g, in which case the input text was again Latin, even though I was supposedly in Japanese input mode (confirmed by cancelling with C-g again and then typing in the Google search bar again).

I always assumed input modes was something that happened on an OS level (although Emacs requires its own setup for Japanese input).

**Comment by Ambrevar** [comment]
> I always assumed input modes was something that happened on an OS level (although Emacs requires its own setup for Japanese input).

Me too! :p

I'm a bit puzzled here, I guess I need to read more about how input
methods work.
Maybe Emacs would be a good starting point indeed.

**Comment by jmercouris** [comment]
Interesting, I can't enter text in Greek on my machine in any field, might have to do with XQuartz though. I can try the native build later.

**Comment by jmercouris** [comment]
Update: I can't even paste on my machine it just shows up as "??????". I can however right click and paste here: ασδφ

**Comment by Ambrevar** [comment]
Strange, pasting in the minibuffer works for me.
Pasting is done with pbcopy on macOS if I'm not mistaken.  Can you
report the result of pasting ασδφ using pbcopy in a shell?

**Comment by jmercouris** [comment]
Yes, so I just tried pbpaste and it works just fine... the PLOT T H I C K E N S :-D

**Comment by acidtoyman** [comment]
I can confirm that pasting Japanese into the minibuffer works for me, but still not Japanese input.

**Comment by jmercouris** [comment]
Greek input works for me now with the native Quartz macOS bindings:

![Screen Shot 2020-07-24 at 11 06 58](https://user-images.githubusercontent.com/1691662/88376490-cfe9ff80-cd9d-11ea-80f3-560b290a2e49.png)

**Comment by Ambrevar** [comment]
How do you input it?
I think for Greek you'd use a greek layout, you don't need an input method.

**Comment by jmercouris** [comment]
Yes, that is correct, you use a Greek layout. Just wanted to follow up on my previous comments. Japanese input is still indeed broken.

**Comment by jmercouris** [comment]
This is now fixed on master! Please let me know if you  have any more issues.

**Comment by acidtoyman** [comment]
Thanks!  Looking forward to trying it out, but I've been having trouble getting things to compile while staying as much as possible on Debian Stable (I've installed SBCL and a few other packages from Testing, but it hasn't helped).

**Comment by acidtoyman** [comment]
I just realized the .deb package has been updated,, and tried it too, but got this:

<INFO> [13:52:29] Listening to socket "/home/my_username/.local/share/nyxt/nyxt.socket".
Nyxt version dont-use-this-tag6
<INFO> [13:52:29] Loading Lisp file "/home/my_username/.config/nyxt/auto-config.lisp".
Unhandled SB-KERNEL::UNDEFINED-ALIEN-FUNCTION-ERROR in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                                                 {100705F893}>:
  The alien function "stat" is undefined.

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {100705F893}>
0: ("undefined function")
1: (ORG.SHIRAKUMO.FILE-ATTRIBUTES::STAT "/home/my_username/.local/share/nyxt/nyxt.socket")
2: (ORG.SHIRAKUMO.FILE-ATTRIBUTES:ATTRIBUTES "/home/my_username/.local/share/nyxt/nyxt.socket")
3: (NYXT::SET-PERMISSIONS "/home/my_username/.local/share/nyxt/nyxt.socket" :GROUP-READ NIL :GROUP-WRITE NIL :GROUP-EXECUTE NIL :OTHER-READ NIL :OTHER-WRITE NIL :OTHER-EXECUTE NIL)
4: (NYXT::LISTEN-SOCKET)
5: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
6: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
7: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
8: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
9: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
10: (SB-THREAD::RUN)
11: ("foreign function: call_into_lisp")
12: ("foreign function: funcall1")

unhandled condition in --disable-debugger mode, quitting
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition

**Comment by Ambrevar** [comment]
This is odd, file-attributes::stat should be portable.

What's your OS and kernel version?

**Comment by acidtoyman** [comment]
my-username@my-laptop:~$ uname -a
Linux my-laptop 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux

**Comment by Ambrevar** [comment]
Your kernel is a bit old.  Could file-attribute be incompatible with it?
I'll ask upstream.

**Comment by Ambrevar** [comment]
@acidtoyman Could you start an SBCL REPL, load https://github.com/Shinmera/file-attributes and run the `ORG.SHIRAKUMO.FILE-ATTRIBUTES:ATTRIBUTES` function on any file?

Let me know if you need help going through these steps.

**Comment by Ambrevar** [comment]
See discussion: https://gitlab.com/ralt/linux-packaging/-/issues/7

**Comment by Ambrevar** [comment]
Looks like you are running Debian (which one?) and this .deb is meant for distros based on Ubuntu 18.04.
I'll edit the download page to clarify this.

**Comment by acidtoyman** [comment]
Yes, I'm running Debian 10 (Stable), with SBCL 2.2.1 from Testing (Stable has only 1.4.16).

Here's the output for ORG.SHIRAKUMO.FILE-ATTRIBUTES:ATTRIBUTES:

CL-USER> (ORG.SHIRAKUMO.FILE-ATTRIBUTES:ATTRIBUTES "/home/my-username/.emacs")
33188

**Comment by Ambrevar** [comment]
OK, thanks for reporting.
For Debian users I recommend to use the Guix pack instead, the Ubuntu
.deb being incompatible.

@jmercouris: Should we provide a .deb for Debian too?

**Comment by acidtoyman** [comment]
I think I'll have to pass for a while, or figure out how to get the source to compile—Guix isn't available in Stable, and I've accidentally borked my system a couple times in the past mixing Stable and Testing (which is a problem for me as I use this laptop for work).

**Comment by acidtoyman** [comment]
I tried using the "All distributions (x86-64)"  download that includes all the dependencies (it's huge!), but no luck here, either.  I get:

my-username@my-laptop:~/bin/nyxt$./usr/local/bin/nyxt 

(process:27605): Gtk-WARNING **: 17:12:11.067: Locale not supported by C library.
	Using the fallback 'C' locale.
<INFO> [17:12:11] Nyxt already started.

**Comment by Ambrevar** [comment]
> (process:27605): Gtk-WARNING **: 17:12:11.067: Locale not supported by C library.
> 	Using the fallback 'C' locale.
> <INFO> [17:12:11] Nyxt already started.

This means that a background Nyxt process is still running.
Kill all nyxt processes, then try again.
In doubt, restart your computer :)

**Comment by acidtoyman** [comment]
You're right—rebooting worked.

Now I can run Nyxt, but input methods have stopped working within Nyxt entirely.  I can't input Japanese, not only in the minibuffer, but anywhere else, either.  I can type special characters using a (remapped) "compose" key (ñōæ), but I can't switch input methods while in Nyxt.

**Comment by Ambrevar** [comment]
How would a reboot affect this?  Did you update anything?
Is this related to #866 somehow?

Can you try re-installing Nyxt?

**Comment by acidtoyman** [comment]
I don't remember updating anything, but I haven't rebooted in a while.

I tried the .deb again, and I get the same problem.  When compiling from source I keep running into problems with cl-webkit:

; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "WEBKIT-DOWNLOAD-CANCEL" not found in the CL-WEBKIT2 package.
;   
;       Line: 916, Column: 53, File-Position: 40997
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/ajm/quicklisp/local-projects/nyxt-master/source/renderer-gtk.lisp" {10078A8FD3}>

; compilation aborted after 0:00:00.488

The only version I can get to run is the "All distributions (x86-64)" download.

The problem is similar to #866, but I was able to use CJK input before—everywhere except in the minibuffer.  I normally don't have to do anything to get CJK input to work with individual applications, with the exception of Emacs.  I add the following to my .emacs to get CJK input (one of a number of ways to get CJK input on Emacs):

(require 'mozc)
(setq default-input-method "japanese-mozc")
(global-set-key (kbd "<zenkaku-hankaku>") 'toggle-input-method)

**Comment by Ambrevar** [comment]
You have Quicklisp installed and the wrong version of cl-webkit.
Can you reinitialize the Nyxt repo (in doubt, remove it and check out
again) and make sure you don't have cl-webkit in your quickdist or in ~/common-lisp?

**Comment by acidtoyman** [comment]
All right, everything seems to work now, as well as CJK input (in the minibuffer, too)!  Thanks!

I'll have to spend some time now familiarizing myself with Nyxt keychords (I've been using Conkeror so long).

**Comment by Ambrevar** [comment]
Glad it's working! :)

So what was the fix in the end?

About the bindings, don't hesitate to send us feedback here: https://github.com/atlas-engineer/nyxt/issues/1248
Also a "Conkeror" scheme could become a popular extension: https://nyxt.atlas.engineer/article/nyxt-extensions-tutorial.org.

**Comment by acidtoyman** [comment]
I removed cl-webkit from the quicklisp directories, re-cloned nyxt and
recompiled.

I was thinking of rebinding to a Conkeror scheme, but I think it might be
better to try to get used to what Nyxt ships with until (unless) I run into
issues.

**Comment by Ambrevar** [comment]
Thanks for the feedback!

**Comment by leephillips** [comment]
I tried both the .deb and the big “all distributions" archive and also can not enter any Unicode or Greek characters in the minibuffer (I guess it’s called). This means I can’t enter URLs, filenames, or anything else as part of commands unless they only contain ASCII. This is the only program I’ve ever run into that has this problem.

I’m on Debian 11 using dwm and no desktop. The compose key and the dead Greek key don’t work with nyxt, but work perfectly in every other browser and program. My entry method configuration is the two lines

    export GTK_IM_MODULE="xim"
    export QT_IM_MODULE="simple"

in my .xinitrc.

I would really like to explore Nyxt, but this is a non-starter.

**Comment by Ambrevar** [comment]
See https://github.com/atlas-engineer/nyxt/issues/2285#issuecomment-1135828424.  I suggest to continue the discussion on #2285.  

XIM does not work indeed, we're investigating.  Ibus is known to work though.

**Comment by Ambrevar** [comment]
Thank you and have fun! :)
